# Generated by Django 3.2.8 on 2022-01-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220129_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='chead1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='chead2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head2',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
