# Generated by Django 3.2.8 on 2022-01-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220129_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='sno',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='chead0',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head0',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tilte',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
