# Generated by Django 3.2.8 on 2022-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220204_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cimages0',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='cimages1',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='cimages2',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
